spring.ai.mcp.server.name=my-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
server.port=8080
spring.ai.mcp.annotation-scanner.enabled=true
spring.ai.mcp.server.protocol=STREAMABLE
